### ISSUE TITLE
`ppm_message` is an invalid type name.

### ISSUE THREAD

**Issue by jo12bar** [UofA-SPEAR/uavcan_dsdl#3]
During buildtime (either with the dsdlc compiler or with canros through catkin), the dsdl parser (which is built with pyuavcan, btw) errors out with the following:

```
No handlers could be found for logger "uavcan.dsdl.parser"
Traceback (most recent call last):
  File "/home/johann/ros/src/canros/scripts/server.py", line 8, in <module>
    import canros
  File "/home/johann/ros/devel/lib/python2.7/dist-packages/canros/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 5, in <module>
  File "/home/johann/.local/lib/python2.7/site-packages/uavcan/__init__.py", line 188, in <module>
    load_dsdl()
  File "/home/johann/.local/lib/python2.7/site-packages/uavcan/__init__.py", line 136, in load_dsdl
    dtypes = dsdl.parse_namespaces(paths)
  File "/home/johann/.local/lib/python2.7/site-packages/uavcan/dsdl/parser.py", line 860, in parse_namespaces
    t = parser.parse(filename)
  File "/home/johann/.local/lib/python2.7/site-packages/uavcan/dsdl/parser.py", line 713, in parse
    raise DsdlException('Internal error: %s' % str(ex), file=filename)
uavcan.dsdl.common.DsdlException: /home/johann/uavcan_vendor_specific_types/spear/general/20200.ppm_message.uavcan: Internal error: /home/johann/uavcan_vendor_specific_types/spear/general/20200.ppm_message.uavcan: Invalid type name [spear.general.ppm_message]
```

Seems that `ppm_message` is an invalid type name. I'm not too familiar with the proper naming conventions. How do we fix this?

**Comment by davidlenfesty** [comment]
Issue fixed by commit cedd063c7bbf9c58265c246dbc51e1d69ec758e1

Turns out the name has to start with a capital letter and underscores are not allowed.

I do need to add checking whether these compile to Travis CI at some point.
